name: kspm_payment_center_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  share: ^2.0.4
  shared_preferences: ^2.2.3
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/kspm-uty-logo.png

fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Black.ttf
      - asset: fonts/Montserrat-BlackItalic.ttf
      - asset: fonts/Montserrat-Bold.ttf
      - asset: fonts/Montserrat-BoldItalic.ttf
      - asset: fonts/Montserrat-ExtraBold.ttf
      - asset: fonts/Montserrat-ExtraBoldItalic.ttf
      - asset: fonts/Montserrat-ExtraLight.ttf
      - asset: fonts/Montserrat-ExtraLightItalic.ttf
      - asset: fonts/Montserrat-Italic.ttf
        style: italic
      - asset: fonts/Montserrat-Light.ttf
      - asset: fonts/Montserrat-LightItalic.ttf
      - asset: fonts/Montserrat-Medium.ttf
      - asset: fonts/Montserrat-MediumItalic.ttf
      - asset: fonts/Montserrat-Regular.ttf
      - asset: fonts/Montserrat-SemiBold.ttf
      - asset: fonts/Montserrat-SemiBoldItalic.ttf
      - asset: fonts/Montserrat-Thin.ttf
      - asset: fonts/Montserrat-ThinItalic.ttf
